# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

  xcversion(version: "~> 12.2.0")

  
  platform :ios do
    desc "Runs iOS tests"
    lane :tests do
      multi_scan(
        scheme: 'websocket-starscreams-ios-application',
        devices: 'iPhone 11 (14.2)',
        try_count: 3, # retry _failing_ tests up to three times^1.
        fail_build: false,
        parallel_testrun_count: 1 # run subsets of your tests on parallel simulators^2
      )
      # run_tests(scheme: "websocket-starscreams-ios-application", devices: "iPhone 11 (14.2)")
    end
  end
